name: biproductions
version: 1.0.0.0
synopsis: Produce Language I with labels in Language R
github: 0iEpFAXv/biproductions.git
homepage: https://github.com/0iEpFAXv/biproductions.git
ghc-options: -Wall -O2

tests:
  biproductions-test:
    main: Main.hs
    source-dirs:
      - test
    buildable: True
    dependencies:
      - biproductions
      - QuickCheck
      
library:
  source-dirs:
    - src
  generated-exposed-modules:
    - BiProductionsLib
    
executables:
  biproductions-exe:
    main: Main.hs
    source-dirs:
      - app
    dependencies:
      - biproductions
      
dependencies:
  - base
  - base-noprelude
  - classy-prelude
  - mtl
  - optparse-applicative
  - singletons
  #Needed for Text.Read
  - text
  - time
  - transformers
      
default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators